/**
 * Unified airport resolver. Merges two datasets:
 *
 *   1. The bundled flightcn airport list (515 major civilian airports,
 *      IATA-only, no military).
 *   2. The extended OurAirports-derived list generated by
 *      scripts/build-airports.mjs — major civilian + military bases,
 *      with both IATA and ICAO codes.
 *
 * The extended dataset is authoritative where both sources have an entry,
 * because it carries ICAO codes. The flightcn entries backfill any
 * civilian airport that somehow didn't make it through the OurAirports
 * filters (none in practice, but better safe than sorry).
 *
 * Resolution accepts IATA (3 letters), ICAO (4 letters), or coordinate
 * pairs. Case-insensitive.
 */
import {
  airports as flightAirports,
  type AirportRef,
} from "@/components/ui/flight-airports";
import {
  EXTENDED_AIRPORTS,
  type ExtendedAirportType,
} from "./extended-airports";

export type ResolvedAirport = {
  /** Display code: IATA if present, otherwise ICAO */
  code: string;
  iata?: string;
  icao?: string;
  name: string;
  city: string;
  country: string;
  latitude: number;
  longitude: number;
  type: ExtendedAirportType;
};

const byIata = new Map<string, ResolvedAirport>();
const byIcao = new Map<string, ResolvedAirport>();
const allUnique = new Set<ResolvedAirport>();

// Seed from the extended dataset first — it carries ICAO codes and military
// entries the bundled flightcn list doesn't have.
for (const a of EXTENDED_AIRPORTS) {
  const code = a.iata ?? a.icao ?? "";
  if (!code) continue;
  const resolved: ResolvedAirport = {
    code,
    iata: a.iata,
    icao: a.icao,
    name: a.name,
    city: a.city,
    country: a.country,
    latitude: a.latitude,
    longitude: a.longitude,
    type: a.type,
  };
  if (a.iata && !byIata.has(a.iata)) byIata.set(a.iata, resolved);
  if (a.icao && !byIcao.has(a.icao)) byIcao.set(a.icao, resolved);
  allUnique.add(resolved);
}

// Backfill from flightcn's bundled dataset for any IATA codes we don't have.
for (const [code, a] of Object.entries(flightAirports)) {
  if (byIata.has(code)) continue;
  const resolved: ResolvedAirport = {
    code,
    iata: code,
    name: a.name,
    city: a.city,
    country: a.country,
    latitude: a.latitude,
    longitude: a.longitude,
    type: "large",
  };
  byIata.set(code, resolved);
  allUnique.add(resolved);
}

/**
 * Resolve a raw user-entered airport token (IATA or ICAO code) to a full
 * airport record. Returns null if the code is unknown. Case-insensitive.
 */
export function resolveAirportCode(raw: string): ResolvedAirport | null {
  const code = raw.trim().toUpperCase();
  if (!code) return null;
  if (code.length === 3) return byIata.get(code) ?? null;
  if (code.length === 4) return byIcao.get(code) ?? byIata.get(code) ?? null;
  return null;
}

/**
 * Convert a resolved airport to the `[lng, lat]` tuple form that flightcn's
 * FlightRoute / FlightMultiRoute accept. We always pass tuples (not codes)
 * because flightcn's internal airport dictionary only covers the 515
 * civilian airports in its bundled list — not military or ICAO-only fields.
 */
export function toLngLat(a: ResolvedAirport): AirportRef {
  return [a.longitude, a.latitude] as [number, number];
}

/**
 * Sort order for the datalist: large civilian airports first (most common
 * inputs), then military bases (user's primary use case), then medium
 * regional. Within each tier, alphabetical by display code.
 */
const TYPE_RANK: Record<ExtendedAirportType, number> = {
  large: 0,
  military: 1,
  medium: 2,
};

let cachedList: ResolvedAirport[] | null = null;

/**
 * Every unique airport in the merged dataset, sorted for datalist display.
 * Memoized — called once per mount of ControlPanel's datalist.
 */
export function getAllListableAirports(): ResolvedAirport[] {
  if (cachedList) return cachedList;
  const list = Array.from(allUnique);
  list.sort((a, b) => {
    const t = TYPE_RANK[a.type] - TYPE_RANK[b.type];
    if (t !== 0) return t;
    const ka = a.iata ?? a.icao ?? "";
    const kb = b.iata ?? b.icao ?? "";
    return ka.localeCompare(kb);
  });
  cachedList = list;
  return list;
}
